title: Mathspp
default_lang: en
author:
  name: 'Rodrigo Gir達o Serr達o'
  email: mathspp@mathspp.com
taxonomies:
  - category
  - tag
  - topic
  - snippet-tags
metadata:
  description: 'The mathspp website is home to some very interesting content about mathematics and programming.'
  author: 'Rodrigo Gir達o Serr達o'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /utils: 'https://localhost:8888'
  '/workshops/(.*)': '/training[301]'
  '/education/(.*)': '/training/$1[301]'
  /education: '/training[301]'
  '/blog/solutions/(.*)': '/blog/problems/$1#solution[301]'
  /github: 'https://github.com/mathspp'
  /twitch: 'https://twitch.tv/mathsppblog'
  /pt/twitch: 'https://mathspp.com/twitch'
  /youtube: 'https://www.youtube.com/channel/UCmJ59I1u8uUl9u3MkEry30w'
  /twitter: 'https://twitter.com/mathsppblog'
routes: null
blog:
  route: /blog
footer-random:
  - '[google](https://google.com)'
  - '[twitter](https://twitter.com)'
